plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bioaether.core'
    compileSdk 34

    defaultConfig {
        applicationId "com.bioaether.core"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "4.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug   // Cambia a tu keystore para producción
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // Nombre del APK de salida
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "BioAetherCore-v${defaultConfig.versionName}-${variant.name}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
